"""add_agent_memory

Revision ID: b6e27e4bdf2f
Revises: 010_multi_tenant_admin
Create Date: 2026-03-26 01:16:05.910263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e27e4bdf2f'
down_revision: Union[str, Sequence[str], None] = '010_multi_tenant_admin'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_run_id', sa.String(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_memories_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('slack_webhook_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('teams_webhook_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('telegram_bot_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('dataset_chunks', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('dataset_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.NUMERIC(precision=384), nullable=True))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telegram_bot_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('teams_webhook_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('slack_webhook_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('agent_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_memories_user_id'))

    op.drop_table('agent_memories')
    # ### end Alembic commands ###
